name: mm4cc-ntfy-${SITE_MODE}
services:
  svc:
    image: binwiederhier/ntfy
    restart: unless-stopped
    command: ["serve"]
    environment:
      - TZ=PT
    volumes:
      - ./cache:/var/cache/ntfy
      - ./etc:/etc/ntfy
    ports:
      - 8081:80
  tunnel:
    image: cloudflare/cloudflared
    env_file: ${SITE_MODE}.env
    command: tunnel run
    restart: unless-stopped
