#!/bin/bash
set -e

if (which docker-compose > /dev/null); then
  # Detected and preferring docker-compose with a hyphen
  exec docker-compose exec svc ntfy "$@"
else
  # Falling back to Compose as a plugin
  exec docker compose exec svc ntfy "$@"
fi
